name: Python Action

on:
  push:
    branches: [ main ]
    paths:
      - 'lista_urls.txt'

jobs:
  build:
    name: Donwload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Python script
        run: python download-img.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: imagenes
          path: imagenes
